-include ../../../header.mk

SRC := c-1.c
INC :=
DEF :=
C_CPP_FLAGS :=
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

#*******************************************************************************

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../../footer.mk
