-include ../../header.mk

SRC := b-1.cpp b-2.c
INC :=
DEF :=
C_CPP_FLAGS :=
CFLAGS :=
CPPFLAGS :=
AFLAGS :=

#*******************************************************************************

LIBDIR :=
LIB :=
LINKED_OBJ :=

-include ../../footer.mk
